# fly.toml app configuration file generated for checkin-everyday on 2023-06-02T19:52:10+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "checkin-everyday"
primary_region = "nrt"

[env]
  PORT = 3000
  SESSION_SECRET = 'secret'
  NODE_ENV = "production"

[deploy]
  release_command = "npm run dbmigrate"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
